CREATE TABLE dbo.Client
(
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  CartId INT NOT NULL REFERENCES dbo.Cart(Id),
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Email VARCHAR(120) NOT NULL,
  Password VARCHAR(50) NOT NULL
)
