CREATE TABLE dbo.Product
(
  Id INT NOT NULL PRIMARY KEY IDENTITY,
  Title NVARCHAR(50) NOT NULL DEFAULT 'No title',
  Img NVARCHAR(120) NULL DEFAULT 'No image',
  Price DECIMAL NULL DEFAULT 0,
  Company NVARCHAR(50) NOT NULL DEFAULT 'No company',
  Info NVARCHAR(800) NOT NULL DEFAULT 'No info'
)